<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<head>

    <!-- Basic Page Needs
  ================================================== -->
	<meta charset="utf-8">
	<title>zFurniture - Free Responsive Html5 Templates</title>
	<meta name="description" content="Free Responsive Html5 Css3 Templates | zerotheme.com">
	<meta name="author" content="www.zerotheme.com">
	
    <!-- Mobile Specific Metas
  ================================================== -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    
    <!-- CSS
  ================================================== -->
  	<link rel="stylesheet" href="css/zerogrid.css">
	<link rel="stylesheet" href="css/style.css">
	<link rel="stylesheet" href="css/menu.css">
	<link rel="stylesheet" href="css/responsiveslides.css">
<section id="container">
	<div class="wrap-container">
		<div class="zerogrid">
			<section class="content-box box-1">
				<div class="row"><!--Start Box--><H1>OUR  ROOMS</H1>
					<div class="col-1-4">
						<div class="wrap-col item">
							<h3 class="item-header"><a href="#">KING SIZE</a></h3>
							<div class="zoom-container">
								<img src="KING.jpg" />
							</div>
							<div class="item-content">
								<span>"STAY  AS  A  KING,  FEEL  AS  A KING".</span><BR>
						<p>WE    PROVIDE   ROYAL   SERVICES   TO   ENHANCE   THE   ROYAL   SURROUNDING SO THAT YOU FEEL  LIKE   A   KING ,  WHER E  YOU   RULE    AND   WE   SERVE.</p>
</div>
</div>
</div>
					<div class="col-1-4">
						<div class="wrap-col item">
							<h3 class="item-header"><a href="#">FAMILY</a></h3>
							<div class="zoom-container">
								<img src="DOUBLE.jpg" />
							</div>
							<div class="item-content">
								<span>"PERFECT FOR THE FUN OF SLEEPING TOGETHER ".</span><BR>
<p>WE  PROVIDE  TWO  SET  OF  BEDS  TO  MAKE  YOU   AND  YOUR  FAMILY  LET  SPEND  MORE  TIME   TOGETHER  WITH YOUR KIDS   DURING  TOUR.</p>	</div>
						</div>
</div>
<div class="col-1-4">
						<div class="wrap-col item">
							<h3 class="item-header"><a href="#">BACHELOR</a></h3>
<div class="zoom-container">
<img src="BACHELOR.jpg" />
</div>
<div class="item-content">
								<span>"A BACHELOR SURROUNDING TO REST ALONE IN PEACE".</span>
<p>WE   PROVIDE  A  PEACEFUL  SURROUNDING  SO  THAT   YOU  PARTY  HARD  WHOLE  DAY  N  REST  WHOLE  NIGHT .</p>				</div>
						</div>
</div>
<div class="col-1-4">
						<div class="wrap-col item">
							<h3 class="item-header"><a href="#">DUET</a></h3>
							<div class="zoom-container">
								<img src="DUET1.jpg" />
							</div>
							<div class="item-content">
								<span>"HAVE YOUR YOU AND ME TIME HERE."</span>
<p>WE PROVIDE SERVICES FOR COUPLES TO MAKE YOUR TIME MEMORABLE AND SPECIAL.</p>				</div>
						</div>
					</div>
				</div>
</section>

</body></html>